### PR TITLE
PHP-ify, i18n, updates to topviews, refactoring, restructuring, oh my!

### PR DESCRIPTION
**Pull request by MusikAnimal**

### CODE REVIEW

**Comment by MusikAnimal** [comment]
Much of this reworking badly needs explaining – namely the duplication of php files (`/views` and `/public`) and why we have individually compiled SASS assets. I will update the README tonight. The goal is to have developer source maps and a more smooth deployment with toollabs's lighttpd. The Gruntfile in general could also use some refactoring, but that can wait.

**Comment by MusikAnimal** [comment]
@kaldari I've updated the README if it helps explains things. You are safe to work off of this branch now if you want – I won't push anything else. Never mind the conflicts with master, that's the temporary notice about the [API bug](https://phabricator.wikimedia.org/T128295).

After this is deployed I'm thinking we should go back to HAML, specifically [MtHaml](https://github.com/arnaud-lb/MtHaml). This would not require Ruby and is a full PHP implementation. I think HAML makes working on views considerably easier, and gives purpose to them living in the `/views` directory. I'll also convert our Sass to Less and then we'll no longer depend on Ruby.

**Comment by MusikAnimal** [comment]
@kaldari This works great, but there is an issue with [requiring via relative path](https://github.com/MusikAnimal/pageviews/commit/42b3d151c6f50b92ea8caa283bf44f37be3a4f04#diff-0a565548a1215fef06c7371699ad359cR12). It works on my machine but not the way I have set it up on Tool Labs. We could make the home directory itself be the git repo and it would work, but I don't consider this very safe. I like having the repo in `~/pageviews` and the production code in `~/public_html`.

My thoughts are that we could set up a PHP config file that sets an environment variable like `PROJECT_ROOT`, which would be `~/pageviews` on Tool Labs. The config file would be in `.gitignore` so you can set it accordingly on your local. I tried to figure this out on my own but alas, I'm not too bright when it comes to PHP =P

Do you think we could do something like this? I've added you to the `pageviews-test` project, feel free to take a stab at it.

**Comment by kaldari** [comment]
@MusikAnimal: I'll see about setting up a local config for the autoload.php require.

**Comment by MusikAnimal** [comment]
Giving it a go!

**Pull request merged**
